name: Add or update an organization
description: Request an organization to be added or updated on edumfa.io
title: "[Org] "
labels: organization
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to add or update an organization to edumfa.io! 
        
        If you want to update an existing organization, please make sure to provide the exact same **Organization Name** as the one already listed on the site.
  - type: input
    attributes:
      label: Organization Name
      description: The name of your organization.
    validations:
      required: true
  - type: input
    attributes:
      label: Organization URL
      description: The URL leading to your organization's website. Should start with `https://`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Organization Image
      description: >
        The image of your organization. Please provide a link or paste the image directly. Preferably with transparent background. Supported formats: PNG, JPEG, WEBP, SVG.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Implementation Phase
      description: What phase of implementation of eduMFA is your organization in?
      options:
        - Evaluation
        - Testing
        - Production
    validations:
      required: true
  - type: input
    attributes:
      label: Approximate user count
      description: The approximate number of users in your organization.
  - type: input
    attributes:
      label: Approximate eduMFA enrolled users
      description: The approximate number of enrolled users to eduMFA. Leave blank if when in evaluation phase.
  - type: dropdown
    attributes:
      label: Token Types
      description: The types of tokens your organization uses. Optional.
      multiple: true
      options:
        - 4Eyes
        - ApplicationSpecificPassword
        - Certificate
        - DayPassword
        - Email
        - HOTP
        - IndexedSecret
        - mOTP
        - OCRA
        - PPR
        - Push
        - Password
        - Questionaire
        - Radius
        - Registration
        - Remote
        - SMS
        - Spass
        - SSH
        - TAN
        - TiQR
        - TOTP
        - U2F
        - VASCO
        - WebAuthn
        - Yubico
        - Yubikey