name: Add Organization to eduMFA
on:
  issues:
    types: [ opened ]

permissions:
  pull-requests: write
  contents: write
  issues: write
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-pull-request:
    if: contains(github.event.issue.labels.*.name, 'organization')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Parse Issue Body
        id: extract_info
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"

          ORG_NAME=$(echo "$ISSUE_BODY" | grep -i '### Organization Name' -A 2 | tail -n1 | xargs)
          ORG_URL=$(echo "$ISSUE_BODY" | grep -i '### Organization URL' -A 2 | tail -n1 | xargs)
          ORG_IMAGE=$(echo "$ISSUE_BODY" | grep -i '### Organization Image' -A 2 | tail -n1 | xargs)
          ORG_PHASE=$(echo "$ISSUE_BODY" | grep -i '### Implementation Phase' -A 2 | tail -n1 | xargs)
          ORG_TOKENS=$(echo "$ISSUE_BODY" | grep -i '### Token Types' -A 2 | tail -n1 | xargs)
          ORG_USER_COUNT=$(echo "$ISSUE_BODY" | grep -i '### Approximate User Count' -A 2 | tail -n1 | xargs)

          # Handle image parsing: check for both URL and markdown image format
          if [[ "$ORG_IMAGE" =~ \!\[.*\]\((.*)\) ]]; then
            ORG_IMAGE="${BASH_REMATCH[1]}"
          fi

          # Replace "_No response_" with null
          if [[ "$ORG_TOKENS" == "_No response_" ]]; then
            ORG_TOKENS="null"
          fi
          if [[ "$ORG_USER_COUNT" == "_No response_" ]]; then
            ORG_USER_COUNT="null"
          fi

          echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV
          echo "ORG_URL=$ORG_URL" >> $GITHUB_ENV
          echo "ORG_IMAGE=$ORG_IMAGE" >> $GITHUB_ENV
          echo "ORG_PHASE=$ORG_PHASE" >> $GITHUB_ENV
          echo "ORG_TOKENS=$ORG_TOKENS" >> $GITHUB_ENV
          echo "ORG_USER_COUNT=$ORG_USER_COUNT" >> $GITHUB_ENV
      - name: Slugify organization name
        uses: rlespinasse/slugify-value@v1
        with:
          key: ORG_NAME
      - name: Download organization image
        run: |
          # Download the image with the original name
          curl -O -J -L "$ORG_IMAGE"
          FILE_NAME=$(ls -t | head -n1)
          EXT="${FILE_NAME##*.}"
          mv "$FILE_NAME" "public/organizations/$ORG_NAME_SLUG.$EXT"
      - name: Update users.json
        run: |
          ORG_ENTRY=$(jq -n \
          --arg name "$ORG_NAME" \
          --arg logo "organizations/$ORG_NAME_SLUG.$EXT" \
          --arg url "$ORG_URL" \
          --argjson userCount "${ORG_USER_COUNT:-null}" \
          --arg phase "$ORG_PHASE" \
          --argjson tokens "$(echo "$ORG_TOKENS" | jq -R 'split(",") | map(select(length > 0)) | map(gsub("^\\s+|\\s+$"; ""))')" \
          '{name: $name, logoSrc: $logo, url: $url, userCount: $userCount, phase: $phase, tokenTypes: $tokens}')

          jq --argjson entry "$ORG_ENTRY" '. += [$entry]' data/users.json > tmp.json && mv tmp.json data/users.json
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/organizations/$ORG_NAME_SLUG.$EXT data/users.json
          git commit -m "Add organization $ORG_NAME"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Added ${{ env.ORG_NAME }} organization"
          branch: 'organization/${{ env.ORG_NAME_SLUG }}'
          delete-branch: true
          title: "[Org] Add ${{ env.ORG_NAME }}"
          body: |
            This PR adds the organization ${{ env.ORG_NAME }} to the site.
            > [!NOTE]
            > This is an automated action.
            
            Closes #${{ github.event.issue.number }}
          labels: organization
          reviewers: luc1412
      - name: Comment on issue
        run: gh issue comment ${{ github.event.issue.number }} --body "Thank you for your submission!\nA pull request has been automatically created to add your organization to the site. If your pull request contains any errors, close this issue and create a new one with the correct information."
